# Generated by Django 5.0.1 on 2024-01-13 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_doors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='door_image',
            field=models.ImageField(default='null', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='door',
            name='door_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='door',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='door',
            table=None,
        ),
    ]
