# Generated by Django 5.0.1 on 2024-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_doors', '0002_door_door_image_door_door_name_door_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='door',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='door',
            table='Door',
        ),
    ]
