# Generated by Django 4.2.6 on 2023-12-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_employee_delete_emplpoyee'),
    ]

    operations = [
        migrations.RenameModel('Employee','Employee')
    ]
