# Generated by Django 4.2.6 on 2023-12-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_employee_salary'),
    ]

    operations = [
    ]
