# Generated by Django 4.2.6 on 2023-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_auto_20231223_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='trainee', max_length=20),
        ),
    ]
